# Generated by Django 5.2.5 on 2025-08-26 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('columns', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.TextField()),
                ('row_number', models.IntegerField()),
                ('csv_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='csv_upload.csvupload')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
